In [19]:
import pandas as pd
import nltk
from nltk import punkt
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from math import log, sqrt
import pandas as pd
import numpy as np
import re
%matplotlib inline
from nltk.tokenize import word_tokenize
from nltk import sent_tokenize
from nltk.corpus import stopwords
stop = set(stopwords.words('english'))
from nltk.stem import WordNetLemmatizer 
from tqdm import tqdm

In [2]:
lemmatizer = WordNetLemmatizer()

In [3]:
tokenizer = word_tokenize

In [4]:
df = pd.read_csv('cleanedManhattanfull.csv')

In [5]:
df.head()

,Unnamed: 0,price,rating,restaurant_id,restaurant_name,review_count,review_1,review_2,review_3,review_4,...,review_130,review_131,review_132,review_133,review_134,review_135,review_136,review_137,review_138,review_139
0,0,$$,4.5,ehUuSk5gPTCQmwS_ubgKRA,Upstate,1788,Had a reservation on Saturday night for dinner...,"While it's not my new go-to place for seafood,...",Mehhhhh. Overrated in my opinion.We walked in ...,"Unfortunately, dinner here was pretty disappoi...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,$$,4.5,ETgJqJHV7BW6pIr9Ox74sA,Amélie,2570,The food and drinks here are both delicious. W...,My boyfriend took me here for my birthday earl...,We came for our anniversary dinner. I got the ...,Came here for a light dinner with my friend an...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,$$,4.0,nU4XBdvxDABXqZ6CnB8Dig,Clinton Street Baking Company,4851,I stopped by here to have brunch on my last da...,"This is probably my favorite brunch in NYC, fe...",Came here many years ago & tried their famous ...,I've heard so much about this place over the y...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,$$,4.5,jjJc_CrkB2HodEinB6cWww,LoveMama,4578,Was here with my boyfriend one Sunday evening ...,My friend and I checked out LoveMama around 6p...,We were vacationing in New York and found this...,While this place may look a little dingy and d...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,$$,4.0,C2o3Iw-DXjoUJFgQIbiqkQ,BoCaphe,1291,I came here with my friend last Saturday becau...,We found this restaurant from the review on ye...,I'm surprised this place has such good reviews...,"When I think of having Vietnamese, I immediate...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
import string 
def remove_punctuations(text):
    for punctuation in string.punctuation:
        text = text.replace(punctuation, '')
    return text

In [7]:
rva = ['review_'+ str(x+1) for x in range(139)]

In [8]:
df = df.drop(columns=['Unnamed: 0'])

In [9]:
df = df.fillna(value=str('none'))

In [10]:
for y in rva:
    df[y] = df[y].apply(remove_punctuations)

In [11]:
for y in rva:
    df[y] = df[y].apply(lambda x: ' '.join([word.lower() for word in x.split() if word not in (stop)]))

In [24]:
df.head()

,price,rating,restaurant_id,restaurant_name,review_count,review_1,review_2,review_3,review_4,review_5,...,review_130,review_131,review_132,review_133,review_134,review_135,review_136,review_137,review_138,review_139
0,$$,4.5,ehUuSk5gPTCQmwS_ubgKRA,Upstate,1788,had reservation saturday night dinner everythi...,while new goto place seafood i still liked itc...,mehhhhh overrated opinionwe walked reservation...,unfortunately dinner pretty disappointing mayb...,this place overrated would give 2 stars we got...,...,none,none,none,none,none,none,none,none,none,none
1,$$,4.5,ETgJqJHV7BW6pIr9Ox74sA,Amélie,2570,the food drinks delicious we started cocktails...,my boyfriend took birthday earlier month it so...,we came anniversary dinner i got first caberne...,came light dinner friend amazing cocktails the...,amelie lively wine bar cheese tapas menu a gre...,...,none,none,none,none,none,none,none,none,none,none
2,$$,4.0,nU4XBdvxDABXqZ6CnB8Dig,Clinton Street Baking Company,4851,i stopped brunch last day nyc good thing i cas...,this probably favorite brunch nyc feel spoiled...,came many years ago tried famous maine blueber...,ive heard much place years knew notorious long...,met friends high expectations sadly i disappoi...,...,none,none,none,none,none,none,none,none,none,none
3,$$,4.5,jjJc_CrkB2HodEinB6cWww,LoveMama,4578,was boyfriend one sunday evening i could happi...,my friend i checked lovemama around 6pm friday...,we vacationing new york found restaurant many ...,while place may look little dingy dirty dont l...,this place packed friday night dont expect com...,...,none,none,none,none,none,none,none,none,none,none
4,$$,4.0,C2o3Iw-DXjoUJFgQIbiqkQ,BoCaphe,1291,i came friend last saturday wanted go nearby s...,we found restaurant review yelp friend wanted ...,im surprised place good reviews one times i fe...,when i think vietnamese i immediately refer ct...,interesting fusion food worth price portions f...,...,none,none,none,none,none,none,none,none,none,none

In [12]:
for y in rva:
    df[y] = df[y].apply(lambda x: ' '.join([lemmatizer.lemmatize(word, pos = 'r') for word in x.split()]))

In [13]:
df.head()

,price,rating,restaurant_id,restaurant_name,review_count,review_1,review_2,review_3,review_4,review_5,...,review_130,review_131,review_132,review_133,review_134,review_135,review_136,review_137,review_138,review_139
0,$$,4.5,ehUuSk5gPTCQmwS_ubgKRA,Upstate,1788,had reservation saturday night dinner everythi...,while new goto place seafood i still liked itc...,mehhhhh overrated opinionwe walked reservation...,unfortunately dinner pretty disappointing mayb...,this place overrated would give 2 stars we got...,...,none,none,none,none,none,none,none,none,none,none
1,$$,4.5,ETgJqJHV7BW6pIr9Ox74sA,Amélie,2570,the food drinks delicious we started cocktails...,my boyfriend took birthday earlier month it so...,we came anniversary dinner i got first caberne...,came light dinner friend amazing cocktails the...,amelie lively wine bar cheese tapas menu a gre...,...,none,none,none,none,none,none,none,none,none,none
2,$$,4.0,nU4XBdvxDABXqZ6CnB8Dig,Clinton Street Baking Company,4851,i stopped brunch last day nyc good thing i cas...,this probably favorite brunch nyc feel spoiled...,came many years ago tried famous maine blueber...,ive heard much place years knew notorious long...,met friends high expectations sadly i disappoi...,...,none,none,none,none,none,none,none,none,none,none
3,$$,4.5,jjJc_CrkB2HodEinB6cWww,LoveMama,4578,was boyfriend one sunday evening i could happi...,my friend i checked lovemama around 6pm friday...,we vacationing new york found restaurant many ...,while place may look little dingy dirty dont l...,this place packed friday night dont expect com...,...,none,none,none,none,none,none,none,none,none,none
4,$$,4.0,C2o3Iw-DXjoUJFgQIbiqkQ,BoCaphe,1291,i came friend last saturday wanted go nearby s...,we found restaurant review yelp friend wanted ...,im surprised place good reviews one times i fe...,when i think vietnamese i immediately refer ct...,interesting fusion food worth price portions f...,...,none,none,none,none,none,none,none,none,none,none

In [21]:
for y in tqdm(rva):
    df['token'+y]= df[y].apply(tokenizer)

  0%|          | 0/139 [00:00<?, ?it/s]
  1%|          | 1/139 [00:11<27:30, 11.96s/it]
  1%|▏         | 2/139 [00:27<30:05, 13.18s/it]
  2%|▏         | 3/139 [00:43<31:08, 13.74s/it]
  3%|▎         | 4/139 [00:56<30:47, 13.68s/it]
  4%|▎         | 5/139 [00:58<22:37, 10.13s/it]
  4%|▍         | 6/139 [01:00<16:55,  7.63s/it]
  5%|▌         | 7/139 [01:01<12:53,  5.86s/it]
  6%|▌         | 8/139 [01:03<10:07,  4.64s/it]
  6%|▋         | 9/139 [01:05<08:10,  3.77s/it]
  7%|▋         | 10/139 [01:07<06:45,  3.14s/it]
  8%|▊         | 11/139 [01:08<05:47,  2.71s/it]
  9%|▊         | 12/139 [01:10<05:04,  2.40s/it]
  9%|▉         | 13/139 [01:12<04:32,  2.16s/it]
 10%|█         | 14/139 [01:13<04:13,  2.02s/it]
 11%|█         | 15/139 [01:15<03:59,  1.93s/it]
 12%|█▏        | 16/139 [01:17<03:48,  1.86s/it]
 12%|█▏        | 17/139 [01:18<03:35,  1.76s/it]
 13%|█▎        | 18/139 [01:20<03:29,  1.73s/it]
 14%|█▎        | 19/139 [01:22<03:30,  1.75s/it]
 14%|█▍        | 20/139 [01:23<03:24,  1.72s/it]
 15%|█▌        | 21/139 [01:25<03:17,  1.68s/it]
 16%|█▌        | 22/139 [01:27<03:18,  1.69s/it]
 17%|█▋        | 23/139 [01:28<03:16,  1.69s/it]
 17%|█▋        | 24/139 [01:30<03:09,  1.65s/it]
 18%|█▊        | 25/139 [01:32<03:10,  1.67s/it]
 19%|█▊        | 26/139 [01:33<03:11,  1.70s/it]
 19%|█▉        | 27/139 [01:35<03:04,  1.65s/it]
 20%|██        | 28/139 [01:37<03:00,  1.62s/it]
 21%|██        | 29/139 [01:38<02:57,  1.61s/it]
 22%|██▏       | 30/139 [01:40<02:56,  1.62s/it]
 22%|██▏       | 31/139 [01:40<02:15,  1.25s/it]
 23%|██▎       | 32/139 [01:41<01:46,  1.01it/s]
 24%|██▎       | 33/139 [01:41<01:25,  1.23it/s]
 24%|██▍       | 34/139 [01:41<01:13,  1.44it/s]
 25%|██▌       | 35/139 [01:42<01:03,  1.64it/s]
 26%|██▌       | 36/139 [01:42<00:56,  1.83it/s]
 27%|██▋       | 37/139 [01:43<00:50,  2.00it/s]
 27%|██▋       | 38/139 [01:43<00:48,  2.08it/s]
 28%|██▊       | 39/139 [01:43<00:46,  2.17it/s]
 29%|██▉       | 40/139 [01:44<00:43,  2.27it/s]
 29%|██▉       | 41/139 [01:44<00:42,  2.31it/s]
 30%|███       | 42/139 [01:45<00:40,  2.38it/s]
 31%|███       | 43/139 [01:45<00:40,  2.38it/s]
 32%|███▏      | 44/139 [01:45<00:38,  2.44it/s]
 32%|███▏      | 45/139 [01:46<00:39,  2.39it/s]
 33%|███▎      | 46/139 [01:46<00:38,  2.44it/s]
 34%|███▍      | 47/139 [01:47<00:36,  2.51it/s]
 35%|███▍      | 48/139 [01:47<00:35,  2.54it/s]
 35%|███▌      | 49/139 [01:47<00:35,  2.56it/s]
 36%|███▌      | 50/139 [01:48<00:34,  2.59it/s]
 37%|███▋      | 51/139 [01:48<00:33,  2.59it/s]
 37%|███▋      | 52/139 [01:49<00:33,  2.59it/s]
 38%|███▊      | 53/139 [01:49<00:34,  2.52it/s]
 39%|███▉      | 54/139 [01:49<00:33,  2.57it/s]
 40%|███▉      | 55/139 [01:50<00:32,  2.58it/s]
 40%|████      | 56/139 [01:50<00:32,  2.53it/s]
 41%|████      | 57/139 [01:50<00:31,  2.58it/s]
 42%|████▏     | 58/139 [01:51<00:31,  2.58it/s]
 42%|████▏     | 59/139 [01:51<00:32,  2.47it/s]
 43%|████▎     | 60/139 [01:52<00:30,  2.55it/s]
 44%|████▍     | 61/139 [01:52<00:30,  2.59it/s]
 45%|████▍     | 62/139 [01:52<00:29,  2.57it/s]
 45%|████▌     | 63/139 [01:53<00:29,  2.59it/s]
 46%|████▌     | 64/139 [01:53<00:28,  2.61it/s]
 47%|████▋     | 65/139 [01:54<00:27,  2.64it/s]
 47%|████▋     | 66/139 [01:54<00:28,  2.60it/s]
 48%|████▊     | 67/139 [01:54<00:27,  2.60it/s]
 49%|████▉     | 68/139 [01:55<00:27,  2.60it/s]
 50%|████▉     | 69/139 [01:55<00:27,  2.53it/s]
 50%|█████     | 70/139 [01:56<00:27,  2.55it/s]
 51%|█████     | 71/139 [01:56<00:26,  2.57it/s]
 52%|█████▏    | 72/139 [01:56<00:26,  2.57it/s]
 53%|█████▎    | 73/139 [01:57<00:25,  2.58it/s]
 53%|█████▎    | 74/139 [01:57<00:24,  2.65it/s]
 54%|█████▍    | 75/139 [01:57<00:24,  2.61it/s]
 55%|█████▍    | 76/139 [01:58<00:23,  2.68it/s]
 55%|█████▌    | 77/139 [01:58<00:23,  2.63it/s]
 56%|█████▌    | 78/139 [01:59<00:24,  2.50it/s]
 57%|█████▋    | 79/139 [01:59<00:24,  2.43it/s]
 58%|█████▊    | 80/139 [01:59<00:23,  2.47it/s]
 58%|█████▊    | 81/139 [02:00<00:22,  2.54it/s]
 59%|█████▉    | 82/139 [02:00<00:22,  2.55it/s]
 60%|█████▉    | 83/139 [02:01<00:21,  2.60it/s]
 60%|██████    | 84/139 [02:01<00:21,  2.61it/s]
 61%|██████    | 85/139 [02:01<00:20,  2.66it/s]
 62%|██████▏   | 86/139 [02:02<00:19,  2.68it/s]
 63%|██████▎   | 87/139 [02:02<00:19,  2.72it/s]
 63%|██████▎   | 88/139 [02:02<00:18,  2.76it/s]
 64%|██████▍   | 89/139 [02:03<00:18,  2.74it/s]
 65%|██████▍   | 90/139 [02:03<00:17,  2.73it/s]
 65%|██████▌   | 91/139 [02:04<00:18,  2.65it/s]
 66%|██████▌   | 92/139 [02:04<00:17,  2.66it/s]
 67%|██████▋   | 93/139 [02:04<00:17,  2.66it/s]
 68%|██████▊   | 94/139 [02:05<00:20,  2.16it/s]
 68%|██████▊   | 95/139 [02:05<00:19,  2.22it/s]
 69%|██████▉   | 96/139 [02:06<00:18,  2.34it/s]
 70%|██████▉   | 97/139 [02:06<00:17,  2.45it/s]
 71%|███████   | 98/139 [02:07<00:16,  2.46it/s]
 71%|███████   | 99/139 [02:07<00:15,  2.51it/s]
 72%|███████▏  | 100/139 [02:07<00:15,  2.57it/s]
 73%|███████▎  | 101/139 [02:08<00:14,  2.65it/s]
 73%|███████▎  | 102/139 [02:08<00:14,  2.64it/s]
 74%|███████▍  | 103/139 [02:08<00:13,  2.66it/s]
 75%|███████▍  | 104/139 [02:09<00:12,  2.71it/s]
 76%|███████▌  | 105/139 [02:09<00:12,  2.65it/s]
 76%|███████▋  | 106/139 [02:09<00:12,  2.68it/s]
 77%|███████▋  | 107/139 [02:10<00:11,  2.72it/s]
 78%|███████▊  | 108/139 [02:10<00:11,  2.71it/s]
 78%|███████▊  | 109/139 [02:11<00:11,  2.67it/s]
 79%|███████▉  | 110/139 [02:11<00:10,  2.71it/s]
 80%|███████▉  | 111/139 [02:11<00:10,  2.71it/s]
 81%|████████  | 112/139 [02:12<00:10,  2.68it/s]
 81%|████████▏ | 113/139 [02:12<00:09,  2.76it/s]
 82%|████████▏ | 114/139 [02:12<00:09,  2.77it/s]
 83%|████████▎ | 115/139 [02:13<00:09,  2.63it/s]
 83%|████████▎ | 116/139 [02:13<00:08,  2.63it/s]
 84%|████████▍ | 117/139 [02:14<00:08,  2.64it/s]
 85%|████████▍ | 118/139 [02:14<00:07,  2.72it/s]
 86%|████████▌ | 119/139 [02:14<00:07,  2.71it/s]
 86%|████████▋ | 120/139 [02:15<00:07,  2.70it/s]
 87%|████████▋ | 121/139 [02:15<00:06,  2.77it/s]
 88%|████████▊ | 122/139 [02:15<00:05,  2.87it/s]
 88%|████████▊ | 123/139 [02:16<00:05,  3.03it/s]
 89%|████████▉ | 124/139 [02:16<00:04,  3.15it/s]
 90%|████████▉ | 125/139 [02:16<00:04,  3.50it/s]
 91%|█████████ | 126/139 [02:16<00:03,  3.87it/s]
 91%|█████████▏| 127/139 [02:17<00:04,  2.49it/s]
 92%|█████████▏| 128/139 [02:17<00:03,  3.15it/s]
 93%|█████████▎| 129/139 [02:17<00:02,  3.88it/s]
 94%|█████████▎| 130/139 [02:17<00:01,  4.65it/s]
 94%|█████████▍| 131/139 [02:17<00:01,  5.49it/s]
 95%|█████████▍| 132/139 [02:18<00:01,  6.23it/s]
 96%|█████████▌| 133/139 [02:18<00:00,  6.57it/s]
 96%|█████████▋| 134/139 [02:18<00:00,  6.75it/s]
 97%|█████████▋| 135/139 [02:18<00:00,  7.33it/s]
 98%|█████████▊| 136/139 [02:18<00:00,  7.52it/s]
 99%|█████████▊| 137/139 [02:18<00:00,  7.91it/s]
 99%|█████████▉| 138/139 [02:18<00:00,  8.10it/s]
100%|██████████| 139/139 [02:18<00:00,  8.10it/s]

In [22]:
df.head()

,price,rating,restaurant_id,restaurant_name,review_count,review_1,review_2,review_3,review_4,review_5,...,tokenreview_130,tokenreview_131,tokenreview_132,tokenreview_133,tokenreview_134,tokenreview_135,tokenreview_136,tokenreview_137,tokenreview_138,tokenreview_139
0,$$,4.5,ehUuSk5gPTCQmwS_ubgKRA,Upstate,1788,"[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' t h i s ' ] , [ ' p l a c e ' ] , [ ...",...,[none],[none],[none],[none],[none],[none],[none],[none],[none],[none]
1,$$,4.5,ETgJqJHV7BW6pIr9Ox74sA,Amélie,2570,"[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' a m e l i e ' ] , [ ' l i v e l y ' ] ...",...,[none],[none],[none],[none],[none],[none],[none],[none],[none],[none]
2,$$,4.0,nU4XBdvxDABXqZ6CnB8Dig,Clinton Street Baking Company,4851,"[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' m e t ' ] , [ ' f r i e n d s ' ] , ...",...,[none],[none],[none],[none],[none],[none],[none],[none],[none],[none]
3,$$,4.5,jjJc_CrkB2HodEinB6cWww,LoveMama,4578,"[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' t h i s ' ] , [ ' p l a c e ' ] , [ ...",...,[none],[none],[none],[none],[none],[none],[none],[none],[none],[none]
4,$$,4.0,C2o3Iw-DXjoUJFgQIbiqkQ,BoCaphe,1291,"[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' [ ' ] , [ ' [ ' ] , [ "" ' "" ] , [ ...","[ [ ' i n t e r e s t i n g ' ] , [ ' f u s ...",...,[none],[none],[none],[none],[none],[none],[none],[none],[none],[none]